### ISSUE TITLE
certificate verify failed after update

### ISSUE THREAD

**Issue by zerodburn** [Shopify/shopify_theme#103]
Hi,

I'm running shopify_theme on Windows 8.1 and everything was working perfectly until I did `gem update shopify_theme`. Now I get the following error after doing `theme watch`:

```
Uploading: templates/index.liquidC:/RailsInstaller/Ruby1.9.3/lib/ruby
/1.9.1/net/http.rb:800:in `connect': SSL_connect returned=1 errno=0 state=SSLv3
read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/net/http.rb:800:in `block in connect'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/net/http.rb:800:in `connect'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/net/http.rb:745:in `start'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/net/http.rb:1285:in `request'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/httparty-0.13.1/lib/httparty/request.rb:93:in `perform'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/httparty-0.13.1/lib/httparty.rb:521:in `perform_request'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/httparty-0.13.1/lib/httparty.rb:483:in `put'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.18/lib/shopify_theme.rb:73:in `send_asset'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.18/lib/shopify_theme/cli.rb:214:in `block in send_asset'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.18/lib/shopify_theme/cli.rb:271:in `show_during'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.18/lib/shopify_theme/cli.rb:213:in `send_asset'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.18/lib/shopify_theme/cli.rb:136:in `block in watch'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.18/lib/shopify_theme/cli.rb:168:in `block in watcher'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/filewatcher-0.3.4/lib/filewatcher.rb:30:in `block in watch'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/filewatcher-0.3.4/lib/filewatcher.rb:24:in `loop'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/filewatcher-0.3.4/lib/filewatcher.rb:24:in `watch'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.18/lib/shopify_theme/cli.rb:167:in `watcher'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.18/lib/shopify_theme/cli.rb:127:in `watch'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/shopify_theme-0.0.18/bin/theme:24:in `<top (required)>'
        from C:/RailsInstaller/Ruby1.9.3/bin/theme:23:in `load'
        from C:/RailsInstaller/Ruby1.9.3/bin/theme:23:in `<main>'
```

I found this link http://docs.shopify.com/api/tutorials/php-api-faq which says

"A. This means that your version of curl is having issues verifying the Shopify store's SSL certificate. To fix this set USE_SSL_PEM to true in your configuration and set CA_PATH to the full path to the provided cacert.pem file.

Windows (note the double slashes!)

define('CA_FILE', 'C:\\path\\to\\cacert.pem');"

However its not clear where to put this line, or where my cacert.pem is?

Please help, thanks.

**Comment by JackWells** [comment]
Helping a friend on Windoze with this.  Tried all listed above to no effect.  Reverted to the version 0.0.17 and it works now.  The "bundling an SSL certificate with the gem" sounds like a great idea - Windows just doesn't work with SSL, in many cases, no matter how many hoops you jump through.

**Comment by csaunders** [comment]
I've deployed a new gem version. This one includes a bundled CA certificate that should resolve any SSL errors Windows users have been experiencing. I did the testing on a Windows 8.1 VM to ensure that it behaves the way we expect.

Please let me know if you have any issues.

**Comment by donlewi** [comment]
Hi there, dealing with exactly this problem on windows 10. see below:
 theme bootstrap *********************** ************************ xxxxxxxxxxxxxx.myshopify.com thingy
Registering xxxxxxxxxxxxxx.myshopify.com
C:/Ruby21/lib/ruby/2.1.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/Ruby21/lib/ruby/2.1.0/net/http.rb:923:in `block in connect'
        from C:/Ruby21/lib/ruby/2.1.0/timeout.rb:75:in `timeout'
        from C:/Ruby21/lib/ruby/2.1.0/net/http.rb:923:in `connect'
        from C:/Ruby21/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
        from C:/Ruby21/lib/ruby/2.1.0/net/http.rb:852:in `start'
        from C:/Ruby21/lib/ruby/2.1.0/net/http.rb:1375:in `request'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/httparty-0.13.7/lib/httparty/request.rb:117:in `perform'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/httparty-0.13.7/lib/httparty.rb:476:in `get'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/httparty-0.13.7/lib/httparty.rb:583:in `get'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/shopify_theme-0.0.25/lib/shopify_theme/releases.rb:17:in `fetch!'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/shopify_theme-0.0.25/lib/shopify_theme/releases.rb:45:in `versioned_releases'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/shopify_theme-0.0.25/lib/shopify_theme/releases.rb:24:in `all'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/shopify_theme-0.0.25/lib/shopify_theme/releases.rb:32:in `find'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/shopify_theme-0.0.25/lib/shopify_theme.rb:88:in `upload_timber'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/shopify_theme-0.0.25/lib/shopify_theme/cli.rb:81:in `bootstrap'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/shopify_theme-0.0.25/bin/theme:26:in `<top (required)>'
        from c:/ruby21/bin/theme:23:in `load'
        from c:/ruby21/bin/theme:23:in `<main>'

I have tried adding a cert, using the later ruby version as well as 32bit and 64bit. above from 2.1 32bit. I also tried making an enviroment vairiable. I have dev tools installed as well.
My main machine is a pc - i use vagrant and can so can setup in ubuntu if needed. but thought id give it a go on windows to begin with.

**Comment by csaunders** [comment]
Check out http://themekit.cat

It should just work.

Chris // developer @ Shopify

**Comment by donlewi** [comment]
Ok this morning I tried again and success in powershell. I use a babun as a console emulator. yesterday it was not working in powershell but it seems to now that i am running ruby 2.1 32bit. It still does not run in babun, but this is most likely a problem with babun accessing the certificates. so all good now.

**Comment by csaunders** [comment]
Could you go over what you did in further detail? I'd like to include some debugging / help docs for windows users.

If you'd like, a PR to some updates on the README would be awesome
